# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(db_column='GROUP_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('area', models.CharField(db_column='Area', max_length=20)),
                ('is_public', models.IntegerField(db_column='Is_public')),
            ],
            options={
                'db_table': 'GROUPS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('time', models.DateTimeField(db_column='Time')),
                ('date', models.DateField(db_column='Date')),
                ('instance_location', models.CharField(db_column='INSTANCE_Location', max_length=20)),
                ('instance', models.AutoField(db_column='INSTANCE_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'INSTANCES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'USERS_GROUPS',
                'managed': False,
            },
        ),
    ]
