# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('text', models.TextField(db_column='Text')),
                ('bp_time', models.DateTimeField(db_column='BP_Time')),
                ('is_public', models.IntegerField(db_column='Is_public')),
                ('post_id', models.AutoField(db_column='POST_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'BLOGPOST',
                'managed': False,
            },
        ),
    ]
