# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game1',
            fields=[
                ('game_id', models.AutoField(db_column='GAME_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('poster', models.TextField(blank=True, db_column='Poster', null=True)),
                ('no_of_players', models.CharField(blank=True, db_column='No_of_players', max_length=20, null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
                ('no_of_sessions', models.CharField(blank=True, db_column='No_of_sessions', max_length=20, null=True)),
                ('age_group', models.CharField(blank=True, db_column='Age_group', max_length=20, null=True)),
                ('competitve_level', models.CharField(blank=True, db_column='Competitve_level', max_length=20, null=True)),
            ],
            options={
                'db_table': 'GAME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group1',
            fields=[
                ('group_id', models.AutoField(db_column='GROUP_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('area', models.CharField(db_column='Area', max_length=20)),
                ('is_public', models.IntegerField(db_column='Is_public')),
            ],
            options={
                'db_table': 'GROUPS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='List1',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=20, null=True)),
                ('ownership', models.IntegerField(db_column='Ownership')),
                ('skill', models.CharField(blank=True, db_column='Skill', max_length=20, null=True)),
            ],
            options={
                'db_table': 'LIST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup1',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'USERS_GROUPS',
                'managed': False,
            },
        ),
    ]
